# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8081
  connection-timeout: 5000ms
  servlet:
    context-path: /fast

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: localhost
    port: 6379
    password: Nannan2017JK    # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  resources:
    add-mappings: false
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates/
    check-template: true
    cache: false
    servlet:
      content-type: text/html
    suffix: .html
    mode: HTML
  rabbitmq:
    virtual-host: /
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.power.modules.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: -1
    logic-not-delete-value: 0
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

myjwt:
  # APP模块，是通过JWT认证的，如果要使用APP模块，则需要修改【加密秘钥】
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7，单位秒
    expire: 604800
    header: token

mq:
  env: local
  basic:
    info:
      queue:
        name: ${mq.env}.middleware.mq.basic.info.queue
      exchange:
        name: ${mq.env}.middleware.mq.basic.info.exchange
      routing:
        key:
          name: ${mq.env}.middleware.mq.basic.info.routing.key
  object:
    info:
      queue:
        name: ${mq.env}.middleware.mq.object.info.queue
      exchange:
        name: ${mq.env}.middleware.mq.object.info.exchange
      routing:
        key:
          name: ${mq.env}.middleware.mq.object.info.routing
  fanout:
    queue:
      one:
        name: ${mq.env}.middleware.mq.fanout.one.queue
      two:
        name: ${mq.env}.middleware.mq.fanout.two.queue
    exchange:
      name:
        ${mq.env}.middleware.mq.fanout.exchange
  topic:
    queue:
      one:
        name: ${mq.env}.middleware.mq.topic.one.queue
      two:
        name: ${mq.env}.middleware.mq.topic.two.queue
    routing:
      key:
        one:
          name: ${mq.env}.middleware.mq.topic.routing.*.key
        two:
          name: ${mq.env}.middleware.mq.topic.routing.#.key
    exchange:
      name: ${mq.env}.middleware.mq.topic.exchange